sudo: required
language: cpp
dist: xenial
compiler: gcc
python: "3.7.1"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10
      - cmake
      - libgl1-mesa-dev
      - libegl1-mesa-dev
install:
  - "[ $CXX = g++ ] && export CXX=g++-10 || true"
# Start python3 environment
  - pyenv shell 3.7.1
# Install conan
  - pip3 install conan --upgrade --user
# Automatic detection of your arch, compiler, etc.
  - conan user
# Enable revisions
  - conan config set general.revisions_enabled=1
before_script:
# Download dependencies, build if pre-built package not available
  - conan install . -if=build -s compiler='gcc' -s compiler.version=10 -s compiler.cppstd=17 --build=outdated
script:
# Build the project
  - conan build . -bf=build
after_script:
# Run unit tests
  - cd build/bin
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib ./GBCEmulatorTestPackage