name: gbcemulator
description: Dart FFI bindings for the GBCEmulator C API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
