name: gbcemulator-ci

on:
  push:
    branches: [ master, dev, ci ]
  pull_request:
    branches: [ master, dev, ci ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conan
        uses: conan-io/setup-conan@v1
        with:
          conan-version: 2.0 # Or specify a specific version
      - name: Cache Conan packages
            uses: actions/cache@v3
            with:
              path: |
                ~/.conan2/p
                ~/.conan2/settings.yml
              key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
      - name: Install dependencies
        run: conan install . -s compiler.cppstd=17 --build=missing -u
      - name: Build
        run: conan build . -s compiler.cppstd=17
